### ISSUE TITLE
Tokens not refreshing after restore

### ISSUE THREAD

**Issue by engwan** [fenichelar/ember-simple-auth-token#71]
There's a bug on this line:

https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L129

```
_this.scheduleAccessTokenRefresh(dataObject.get(_this.tokenExpireName), token);
```

`dataObject` contains the expiry time at the `expiresAt` key when authenticating. Ref: https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L176-178

So it's either we retrieve `'expiresAt'` from `dataObject` or retrieve `_this.tokenExpireName` from `tokenData`.

Actually, there's a bit of redundant code in here.
1. The expiry is retrieved incorrectly in https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L107 (This will always be undefined unless `tokenExpireName` happens to be `'expiresAt'`.
2. Since `expiresAt` will always be undefined above, it is correctly retrieved in https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L113-L121 (This retrieves expiry from `tokenData`).
3. The correct expiry retrieved above is now saved in the `expiresAt` variable, but is not the one passed to `scheduleAcessTokenRefresh`.

The offending line can be changed to:

```
_this.scheduleAccessTokenRefresh(expiresAt, token);
```

**Comment by engwan** [comment]
Actually I just realized these last 2 commits break this functionality:
https://github.com/jpadilla/ember-cli-simple-auth-token/commit/5d901e613a4b14295bc22d1be5deab7fc9294262#diff-b3b19e97b14851cfabb1e6558abfc6da
https://github.com/jpadilla/ember-cli-simple-auth-token/commit/95506af4bd2353f975dfcc9ac58bc662b0781d69#diff-b3b19e97b14851cfabb1e6558abfc6da

Maybe @erichonkanen can comment on why these were done?

EDIT: 

Okay I get the first commit now, we need the original unresolved expiry time passed to `scheduleAccessTokenRefresh` because `resolve()` will be called twice.

But https://github.com/jpadilla/ember-cli-simple-auth-token/commit/95506af4bd2353f975dfcc9ac58bc662b0781d69#diff-b3b19e97b14851cfabb1e6558abfc6da should be reverted because the expiry is always stored in `"expiresAt"` and not based on `tokenExpireName`. This can be seen in https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L176-178

Correct code should be:

```
_this.scheduleAccessTokenRefresh(dataObject.get('expiresAt'), token);
```

or

```
_this.scheduleAccessTokenRefresh(tokenData[_this.tokenExpireName], token);
```

**Comment by erichaus** [comment]
hey @engwan, as far as I recall it was changed because previously the name was hardcoded as "expiresAt" whereas the name might have been set differently via `tokenExpireName`

per your edit, yes! I had started looking into why restore isnt working a week or so ago but ive been super busy and I hadn't got to resolving it!

https://github.com/erichonkanen/ember-cli-simple-auth-token/blob/fix_restore/addon/authenticators/jwt.js#L177

that said if I recall last week, I fixed that but it didnt fix the restore functionality... will try again or feel free to submit a PR if you resolve it...

**Comment by engwan** [comment]
On first look, that should fix it, I'll check that branch out and find out why it's not working.

This code though https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L113-L121 I think should be changed to just:

```
if (Ember.isEmpty(expiresAt)) {
  return resolve(data);
}
```

Because it's useless getting `expiresAt` from `tokenData` but then the one passed to `scheduleAccessTokenRefresh` is from `dataObject` anyway.

**Comment by engwan** [comment]
@erichonkanen I checkout out your branch and refreshing of tokens work after restore.

So I'll just wait for https://github.com/jpadilla/ember-cli-simple-auth-token/pull/69 to be merged.

Or was there a specific problem you encountered with the fix you did?

**Comment by erichaus** [comment]
@engwan oh it did work? strange! it wasn't working for me when I had tried but maybe my cache wasn't clear or something.. will try again today and hopefully we can get a fix merged in asap...

**Comment by engwan** [comment]
Yeah, hopefully we can have the PR merged soon since it's a pretty big bug.

**Comment by erichaus** [comment]
@engwan just ran through this again and I'm still getting blank screen after refresh despite updating [this](https://github.com/erichonkanen/ember-cli-simple-auth-token/commit/c767da5d0790bdad5f28dd2bdbca3a3dddad9b91#diff-b3b19e97b14851cfabb1e6558abfc6daR173)

it definitely is something that happens with the latest ember-simple-auth package so I'm not sure if its a change to that package or something wrong in this one, the author of that package didn't seem eager to help when I opened an issue there...

it seems like the `restore` method is not resolving properly...

if you have been able to get it working please paste the steps and your package.json/bower.json as well, thanks!

**Comment by engwan** [comment]
I think that might be due to a different bug. Are you using a custom authenticator / authorizer?

Because there was a breaking change where instead of accessing stuff like: `session.token` or `session.user_id` it is now in `session.secure.token` and `session.secure.user_id`

**Comment by erichaus** [comment]
@engwan Im using the `jwt` authenticator... yes they added the `secure` wrapper but afaik the authorizer in this package already handles it

**Comment by engwan** [comment]
Yes, the packaged authorizer should handle it. Any error you see in the console?

If you can recreate it into a fiddle or sample app I can look into it more.

**Comment by erichaus** [comment]
i'll have to set up a fiddle in a bit but I get blank white screen after page refresh

**Comment by erichaus** [comment]
when I turn on debugging I get this:

`ember-resolver.js:329 [ ] controller:index ........................................... undefined
ember-resolver.js:329 [ ] controller:index ........................................... picstream/controllers/index
ember-resolver.js:329 [ ] controller:index ........................................... undefined
ember.js:47521 Transition #0: index: transition was aborted`

**Comment by engwan** [comment]
That's weird. By "blank white screen after page refresh" you mean after you're already signed in right?

I'm using ember-cli-simple-auth 0.8.0-beta.3 with ember-cli-simple-auth-token 0.7.2, and the only problem was that after a page refresh, the token wasn't getting refreshed correctly (the one fixed by your PR). I didn't encounter that white screen.

**Comment by erichaus** [comment]
@engwan yes I log into the test app, then do a page refresh and it just goes white, no errors in console or anything...

now Im wondering if I have a bug in my demo app.. maybe its bc I upgraded ember to 1.9.1 (tried latest 1.13.2 also)

but the weird thing is that I didnt change anything else in this test app and its worked fine up until upgrading the this app and the simple auth app with it...

**Comment by engwan** [comment]
Do you have a public site for the demo where I can take a look? Or perhaps github repo that I can replicate?

**Comment by erichaus** [comment]
hey @engwan, I just made the test app public https://github.com/epicowl/picstream-frontend, feel free to check it out and let me know if you see anything that sticks out..

the backend is using https://github.com/GetBlimp/django-rest-framework-jwt and this payload handler

```
def jwt_payload_handler(user):
    """
    Used by rest framework JWT.
    """
    try:
        username = user.get_username()
    except AttributeError:
        username = user.username

    return {
        'user': user.pk,
        'email': user.email,
        'username': username,
        'exp': datetime.datetime.utcnow() + api_settings.JWT_EXPIRATION_DELTA
    }

```

**Comment by engwan** [comment]
This is the first one I noticed, on your application route:

```
@store.find 'user', @get 'session.user.username'
```

It should probably be `session.secure.username` or `session.secure.user.username` depending on what you return from the server. Everything returned from the server during authentication will be in the `secure` namespace of the session.

**Comment by erichaus** [comment]
ooommmgggg @engwan I think that was it!! THANKS!... damnit I didnt even realize I had that, the test app is one that was slapped together from piece of another app

**Comment by erichaus** [comment]
should be fixed with https://github.com/jpadilla/ember-cli-simple-auth-token/pull/73

**Comment by engwan** [comment]
:+1: Hope it gets merged soon.

**Comment by erichaus** [comment]
thanks again! that drove me crazy
